base_directory: static
scratch_directory: tmp
station:
  name: sbs3
  touchscreen: false
  model: large dark rig
  capture_directory: capture
  calibration_directory: calibration
  daily_directory: daily
  test_directory: test
  has_bottom_shot: true
  top_shots: 4
  front_shots: 72
  ortho_shots: 72
  has_plank: false
resources:
 - type: ArtProjectCamera
   name: ortho_camera
   model: Canon 5DM3
   position: ORTHO
   camera_number: 10
   inventory_id: NO INVENTORY ID
   guid: 346dbd5
   focal_length_mm: 50
   inverted: true
   aperture: 18
   shutterspeed: 1/10
   iso: 100
   crop_rectangle: ( 798, 0, 4818, 3744 )
   server_url: localhost:8090
 - type: ArtProjectCamera
   name: front_camera
   model: Canon 5DM3
   position: FRONT
   camera_number: 20
   angle_degrees: 15
   inventory_id: NO INVENTORY ID
   guid: bb56b968446f48968d7794801a534ef7
   focal_length_mm: 50
   aperture: 18
   shutterspeed: 1/10
   iso: 100
   crop_rectangle: ( 798, 0, 4818, 3744 )
   server_url: localhost:8091
 - type: ArtProjectCamera
   name: top_camera
   model: Canon 5DM3
   position: TOP
   camera_number: 30
   inventory_id: NO INVENTORY ID
   guid: 160fe898dd24e6d
   focal_length_mm: 35
   aperture: 18
   shutterspeed: 1/15
   iso: 100
   crop_rectangle: ( 798, 0, 4818, 3744 )
   server_url: localhost:8092
 - type: CanonCamera
   name: bottom_camera
   model: Canon T2i
   position: BOTTOM
   camera_number: 40
   inventory_id: NO INVENTORY ID
   guid: 2a5870eeda3049f6b6b7d97af6eb8b3e
   focal_length_mm: 100
   aperture: 18
   shutterspeed: 1/8
   iso: 200
   crop_rectangle: ( 1100, 20, 4590, 3450 )
 - type: WebCamera
   name: builtin_camera
   position: PREVIEW
   camera_number: 100
   inventory_id: NO INVENTORY ID
   port: /dev/v4l/by-id/usb-046d_0823_9ABA64A0-video-index0
 - type: ImsStepper
   name: turntable
   address: 192.168.33.1
   port: 503
   steps: 1218863
   delay_per_step: 0.00005
   init_cmds:
     - hc 0
     - rc 85
     - p 0
     - a 80000
     - d 80000
     - vm 500000
 - type: LightingController
   name: lighting
   handle: /dev/dmx
   front_lights: [1, 2, 3]
   top_lights: [1, 2, 3]
   preview_lights: [2, 3]
   bottom_lights: [4]
 - type: Crosshair
   name: crosshair
   address: 192.168.101.2
 - type: Scanner2d
   name: scan2d
   scan_segments: 72
   table_type: WHITE_WOOD
   capture_alternate_lighting: false
   resources:
    - front_camera
    - top_camera
    - ortho_camera
    - builtin_camera
    - turntable
    - lighting
    - crosshair
   starting_rotation_angle: 90
 - type: OrthoTable
   name: ortho_table
   table_type: GLASS
   starting_rotation_angle: 270
   capture_alternate_lighting: false
   resources:
    - bottom_camera
    - scan2d
    - lighting
credentials:
 - type: ServiceAccount
   service_account_email: 682015002700-5gmoofr8s80voejnr8ld9h2nns2gvfcn@developer.gserviceaccount.com
   service_account_name: 682015002700-5gmoofr8s80voejnr8ld9h2nns2gvfcn.apps.googleusercontent.com
   private_key_file: keys/0d972c7184df27f390eb32ce3b3e68ec4ce5d9b9-privatekey.p12
   name: service
storage:
 - type: BigStore
   bucket: objects3d-scans-sb
   name: bigstore
packer:
  type: Tarball
  name: tarball
  output_directory: static/tarballs
